name: default

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # https://github.com/actions/checkout
      - name: Checkout repository
        uses: actions/checkout@v7
        with:
          fetch-depth: 0

      # https://github.com/actions/setup-dotnet
      - name: Setup dotnet 10.0.x
        uses: actions/setup-dotnet@v6
        with:
          dotnet-version: 10.0.x
    
      # https://docs.github.com/en/actions/how-tos/write-workflows/choose-what-workflows-do/add-scripts
      # https://docs.github.com/en/actions/reference/workflows-and-actions/workflow-syntax#jobsjob_idstepsshell
      - name: Show debug info
        shell: pwsh
        run: ./build/ShowDebugInfo.ps1

      - name: Build simulation library
        shell: pwsh
        run: ./build/BuildSimulation.ps1

      - name: Build game backend
        shell: pwsh
        run: ./build/BuildGameBackend.ps1
        env:
          # https://docs.github.com/en/actions/reference/workflows-and-actions/contexts#github-context
          GITHUB_USER: ${{ github.actor }}
          # https://docs.github.com/en/actions/reference/workflows-and-actions/contexts#secrets-context
          GITHUB_TOKEN: ${{ secrets.PACKAGING_TOKEN }}

      - name: Push Git tag
        shell: pwsh
        run: ./build/PushGitTag.ps1
